require('idris2').setup({})
local bufopts = { noremap = true }
vim.keymap.set('n', '<leader>e', ':lua require("idris2.repl").evaluate()<CR>', bufopts)
vim.keymap.set('n', '<leader>cs', ':lua require("idris2.code_action").case_split()<CR>', bufopts)
vim.keymap.set('n', '<leader>mc', ':lua require("idris2.code_action").make_case()<CR>', bufopts)
vim.keymap.set('n', '<leader>ml', ':lua require("idris2.code_action").make_lemma()<CR>', bufopts)
vim.keymap.set('n', '<leader>ac', ':lua require("idris2.code_action").add_clause()<CR>', bufopts)
vim.keymap.set('n', '<leader>es', ':lua require("idris2.code_action").expr_search()<CR>', bufopts)
vim.keymap.set('n', '<leader>gd', ':lua require("idris2.code_action").generate_def()<CR>', bufopts)
vim.keymap.set('n', '<leader>rh', ':lua require("idris2.code_action").refine_hole()<CR>', bufopts)
vim.keymap.set('n', '<leader>i', ':lua require("idris2.code_action").intro()<CR>', bufopts)
